### ISSUE TITLE
Make it possible to put the language in the URL

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/ideas#17]
As described some time ago by Nachenko in [the forum]([https://www.impresscms.org/modules/iforum/viewtopic.php?topic_id=4020&forum=55&post_id=36841]), it would benefit multilanguage sites to have the language in the URL somewhere. It would be possible to make links directly to the correct language page, and it would help SEO as well.

This could have quite some ramifications if we want to do it correctly, so don't underestimate :-)

**Comment by MekDrop** [comment]
https://github.com/middlewares/negotiation#contentlanguage has possibility to detect language from browser or from url. Probably we could use such middleware for this problem solving.
