### ISSUE TITLE
Drop support for OpenID

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/ideas#20]
The version for OpenID that we support is old, clunky and no longer supported by the majority of the web. The library used is no longer actively maintained, so we might get into problems supporting newer php versions (was this tested under php7 already?).
I propose we just drop this functionality and look to integrate a more modular approach that gives us google, facebook. twitter logins using oauth2, like mentioned in ImpressCMS/impresscms#148 .

**Comment by MekDrop** [comment]
Implemented in [Remove OpenID support #550](https://github.com/ImpressCMS/impresscms/pull/550).

Sorry, @fiammybe I missed this ticked and haven't seen that you where self assigned... I hope this doesn't rise any big problems :|
