### ISSUE TITLE
use composer to check for environment correctness

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/ideas#29]
Composer has the ability to check for the correctness of the environment. See https://getcomposer.org/doc/04-schema.md#package-links

**Comment by fiammybe** [comment]
Composer can verify various aspects of the environment in which it is running. We could use this functionality perhaps to let composer do the detection of some of the parts of our pre-installation check for us.

**Comment by MekDrop** [comment]
Required php extensions now are defined in composer.json and I think that is enough for now to think, that this issue was implemented, that's why I'm closing this ticket.
